### ISSUE TITLE
data processing problem

### ISSUE THREAD

**Issue by wang-zm18** [naver/PoseGPT#2]
Hello, Mr.Lucas. Thanks for your nice work. When I tried to process the smplx data of amass, following your tutorial. However, it always occurs the `out of index` error. The smplh data processing is normal, not like this. I do not know what is the problem. Thank you in advance!
![image](https://user-images.githubusercontent.com/47704679/207863813-c0e81d59-289d-4670-8722-535d25f5caad.png)

**Comment by fabienbaradel** [comment]
Hi @wang-zm18,
Are you using python3 for running the code? Given the log that you are sending it seems that you are using python2 if I am not mistaken..

**Comment by wang-zm18** [comment]
Thank you for your reply! I did use python3 to run the code. The running command is just copied  from your readme.

**Comment by HappyPiepie** [comment]
Hello, Mr.Lucas. Thanks for your nice work,too. I have a problem when i run babel_dir='/home/beibeigh/Reserach/Projects/PoseGPT-main/data/babel'
amass_dir='/home/beibeigh/Reserach/Projects/PoseGPT-main/data/amass/'
mocap_dir='/home/beibeigh/Reserach/Projects/PoseGPT-main/data/preprocesed_data'
list_split=( 'train' 'test' 'val' )
list_type=( 'smplx' 'smplh' )
for split in "${list_split[@]}"
do
    for type in "${list_type[@]}"
    do
        echo ${type}
        echo ${split}
        python dataset/preprocessing/babel.py "prepare_annots_trimmed(type='${type}',split='${split}',mocap_dir='${mocap_dir}',babel_dir='${babel_dir}',amass_dir='${amass_dir}')"
    done
done

And i have the problem:
Traceback (most recent call last):
  File "dataset/preprocessing/babel.py", line 14, in <module>
    from threed.skeleton import *
ModuleNotFoundError: No module named 'threed'

**Comment by HappyPiepie** [comment]
Hello, Mr.Lucas. Thanks for your nice work,too. I have a problem when i run babel_dir='/home/beibeigh/Reserach/Projects/PoseGPT-main/data/babel'
amass_dir='/home/beibeigh/Reserach/Projects/PoseGPT-main/data/amass/'
mocap_dir='/home/beibeigh/Reserach/Projects/PoseGPT-main/data/preprocesed_data'
list_split=( 'train' 'test' 'val' )
list_type=( 'smplx' 'smplh' )
for split in "${list_split[@]}"
do
for type in "${list_type[@]}"
do
echo ${type}
echo ${split}
python dataset/preprocessing/babel.py "prepare_annots_trimmed(type='${type}',split='${split}',mocap_dir='${mocap_dir}',babel_dir='${babel_dir}',amass_dir='${amass_dir}')"
done
done

And i have the problem:
Traceback (most recent call last):
File "dataset/preprocessing/babel.py", line 14, in
from threed.skeleton import *
ModuleNotFoundError: No module named 'threed'

**Comment by LvXinTao** [comment]
> Hello, Mr.Lucas. Thanks for your nice work,too. I have a problem when i run babel_dir='/home/beibeigh/Reserach/Projects/PoseGPT-main/data/babel' amass_dir='/home/beibeigh/Reserach/Projects/PoseGPT-main/data/amass/' mocap_dir='/home/beibeigh/Reserach/Projects/PoseGPT-main/data/preprocesed_data' list_split=( 'train' 'test' 'val' ) list_type=( 'smplx' 'smplh' ) for split in "${list_split[@]}" do for type in "${list_type[@]}" do echo ${type} echo ${split} python dataset/preprocessing/babel.py "prepare_annots_trimmed(type='${type}',split='${split}',mocap_dir='${mocap_dir}',babel_dir='${babel_dir}',amass_dir='${amass_dir}')" done done
> 
> And i have the problem: Traceback (most recent call last): File "dataset/preprocessing/babel.py", line 14, in from threed.skeleton import * ModuleNotFoundError: No module named 'threed'

It's probably because it cannot find the threed module in the repo.
You can add 

`import sys\\
import os\\
sys.path.append(os.getcwd())`
in data/preprocessing/babel.py

**Comment by LeonShangguan** [comment]
@wang-zm18 I solved the issue by adding `if start>=len(fullpose): continue` between line 277-278 in babel.py. I am not sure if this would cause incomplete data process and affect training, could you please kindly check if it matters @fabienbaradel?
